import type { LucideIcon } from "lucide-react";
import { BookOpen, Bot, Cloud, Database, FileText, LockKeyhole, Network, ShieldCheck } from "lucide-react";

export type ConceptStatus = "implemented" | "simulated" | "reserved";

export interface AcademyConcept {
  id: string;
  title: string;
  summary: string;
  math?: string;
  tradeoffs: string;
  security?: string;
  practicalUse: string;
  status: ConceptStatus;
}

export interface AcademyModule {
  id: string;
  title: string;
  icon: LucideIcon;
  intro: string;
  concepts: AcademyConcept[];
}

export const academyModules: AcademyModule[] = [
  {
    id: "ml-foundations",
    title: "ML foundations",
    icon: BookOpen,
    intro: "The general machine-learning mechanics every track in this federation builds on, before anything imaging- or federation-specific is added.",
    concepts: [
      {
        id: "supervised-unsupervised-self-supervised",
        title: "Supervised, unsupervised & self-supervised learning",
        summary: "Three learning regimes distinguished by what supervises the loss: ground-truth labels, structure in unlabeled data, or labels manufactured from the data itself.",
        math: "Supervised: minimize E(x,y)~D [L(f_θ(x), y)]. Self-supervised swaps y for a pretext target y′ derived from x alone (e.g. a masked or transformed view).",
        tradeoffs: "Supervised learning needs radiologist-graded labels, the scarcest resource in medical imaging; self-supervised pretraining can exploit unlabeled archives, but its pretext task must actually transfer to the clinical target — that has to be validated, not assumed.",
        practicalUse: "Every learning track here (chest X-ray, brain MRI, CT) is defined as a supervised task with a named primary metric. Self-supervised pretraining across sites is not implemented.",
        status: "reserved",
      },
      {
        id: "task-types",
        title: "Classification, regression, detection & segmentation",
        summary: "Four output shapes a model can produce: a class label, a continuous value, a bounding box with a class, or a per-pixel/voxel label map.",
        tradeoffs: "Segmentation and detection need denser, costlier annotation than classification, but they answer 'where,' which classification cannot.",
        practicalUse: "The three tracks map directly onto three task types: chest X-ray is classification, brain MRI is segmentation, CT lesion work is detection — each exposed with a task-appropriate primary metric.",
        status: "implemented",
      },
      {
        id: "architectures",
        title: "Neural networks, convolutions, attention & transformers",
        summary: "Convolutions exploit spatial locality and weight sharing for images; attention lets a model weigh relationships between any two positions regardless of distance.",
        math: "Convolution: y[i] = Σ_k w[k]·x[i+k]. Scaled dot-product attention: softmax(QKᵀ/√d)V.",
        tradeoffs: "CNNs are sample-efficient and cheap for local patterns like edges and textures; transformers capture long-range dependencies but usually need more data or careful pretraining to match that efficiency.",
        practicalUse: "Track metadata names a concrete architecture per task (DenseNet-121, 3D U-Net, RetinaNet) so the model choice is visible, but no network actually executes in this console.",
        status: "reserved",
      },
      {
        id: "training-loop",
        title: "Forward pass, backpropagation, loss functions & optimizers",
        summary: "The forward pass computes a prediction and a loss; backpropagation applies the chain rule to get the loss gradient with respect to every weight; the optimizer uses that gradient to update the weights.",
        math: "SGD with momentum: v_(t+1) = βv_t + ∇θ L(θ_t); θ_(t+1) = θ_t − η·v_(t+1).",
        tradeoffs: "Learning rate and optimizer choice trade convergence speed against stability — too high diverges, too low wastes compute and rounds.",
        practicalUse: "Referenced only as labels ('FedAvg', 'FedProx', 'FedOpt' per track) — no gradient computation runs in this console.",
        status: "reserved",
      },
      {
        id: "regularization",
        title: "Regularization, dropout, weight decay & early stopping",
        summary: "Techniques that trade training-set fit for generalization: dropout randomly zeroes activations, weight decay penalizes large weights, early stopping halts training at the point of best held-out performance.",
        math: "Weight decay adds λ‖θ‖² to the loss; dropout scales activations by a Bernoulli mask during training.",
        tradeoffs: "Too much regularization underfits a genuinely complex imaging task; too little lets a model memorize site-specific noise instead of clinical signal.",
        practicalUse: "Not exposed — this console reports outcome metrics, not the training controls that produced them.",
        status: "reserved",
      },
      {
        id: "augmentation-transfer",
        title: "Data augmentation & transfer learning",
        summary: "Augmentation synthesizes label-preserving variations (rotation, intensity jitter) to expand effective sample size; transfer learning reuses weights pretrained on a related task or dataset.",
        tradeoffs: "Augmentations must respect imaging physics — a horizontal flip that's harmless for a natural photo can invert clinically meaningful laterality on a chest X-ray.",
        practicalUse: "Not implemented in this console; each track is assumed to start from an architecture appropriate to its modality rather than a specific pretrained checkpoint.",
        status: "reserved",
      },
      {
        id: "class-imbalance",
        title: "Class imbalance and sampling",
        summary: "Medical findings are rare by nature, so naive training on raw prevalence biases a model toward always predicting 'normal.'",
        math: "Focal loss down-weights easy examples: FL(p_t) = −(1−p_t)^γ · log(p_t), reducing the loss contribution of the abundant majority class.",
        tradeoffs: "Oversampling the minority class or reweighting the loss improves sensitivity to rare findings, but pushed too far it inflates the false-positive rate.",
        practicalUse: "Each track reports sensitivity/specificity or precision/recall precisely because global accuracy alone would hide this problem. PneumoniaMNIST, the real dataset now used for the chest X-ray track's training run, does have real class imbalance (pneumonia cases outnumber normal), but no resampling or reweighting technique (oversampling, focal loss, class weighting) is applied to it — training just runs on the raw distribution. The other two tracks remain fully synthetic.",
        status: "simulated",
      },
      {
        id: "calibration-uncertainty",
        title: "Calibration and uncertainty estimation",
        summary: "A calibrated model's predicted probability matches its empirical accuracy; uncertainty estimation additionally reports how confident the model is in a given prediction.",
        math: "Expected Calibration Error bins predictions by confidence and averages |accuracy − confidence| per bin, weighted by bin size.",
        tradeoffs: "A model can be accurate but badly calibrated — confidently wrong — which is dangerous for any workflow where a human trusts a reported probability.",
        practicalUse: "The training round view surfaces a static calibration figure (ECE) alongside precision/recall as a placeholder for a real calibration pipeline.",
        status: "simulated",
      },
    ],
  },
  {
    id: "medical-imaging",
    title: "Medical imaging ML",
    icon: FileText,
    intro: "How modality, task shape, and annotation quality change the learning problem, and the metric family used to judge it.",
    concepts: [
      {
        id: "dicom-metadata",
        title: "DICOM and metadata boundaries",
        summary: "DICOM files bundle pixel data with metadata (patient ID, institution, scanner model, acquisition parameters) — the metadata is itself a re-identification risk, separate from the image.",
        tradeoffs: "Stripping metadata protects privacy but can remove information (scanner make, protocol) that matters for detecting domain shift.",
        practicalUse: "This console never ingests real DICOM; track descriptions state only the modality. Metadata-handling boundaries are documentation, not code.",
        status: "reserved",
      },
      {
        id: "normalization-preprocessing",
        title: "Image normalization and preprocessing",
        summary: "Raw pixel intensities differ by scanner and protocol (e.g. Hounsfield units in CT, arbitrary units in MRI); normalization rescales them to a consistent range before a model sees them.",
        tradeoffs: "Aggressive normalization can erase real inter-site signal; too little leaves the model fitting scanner artifacts instead of anatomy.",
        practicalUse: "Not implemented — no pixel data flows through this console.",
        status: "reserved",
      },
      {
        id: "modality-workflows",
        title: "CT, MRI, X-ray, ultrasound & pathology workflows",
        summary: "Each modality has a distinct acquisition geometry and noise profile: CT is volumetric with dose tradeoffs, MRI is volumetric with long acquisition and multiple sequences, X-ray is a 2D projection, ultrasound is real-time and operator-dependent, pathology is gigapixel-scale.",
        tradeoffs: "A model architecture tuned for one modality rarely transfers cleanly to another without modality-specific adaptation.",
        practicalUse: "Three of these workflows are represented as named tracks (chest X-ray, brain MRI, CT); ultrasound and pathology are documented but have no track.",
        status: "simulated",
      },
      {
        id: "dimensionality",
        title: "2D versus 3D models",
        summary: "2D models process single slices independently; 3D models consume a full volume and can exploit inter-slice context at the cost of far higher memory and compute.",
        tradeoffs: "3D typically improves segmentation of volumetric structures but multiplies GPU memory requirements, often forcing patch-based training.",
        practicalUse: "The brain MRI track names a 3D U-Net to reflect this tradeoff explicitly; no volumetric inference actually runs.",
        status: "reserved",
      },
      {
        id: "imaging-task-types",
        title: "Classification, lesion detection & semantic segmentation",
        summary: "The imaging-specific instances of the general task types: image-level classification, box-level lesion detection, and pixel/voxel-level segmentation.",
        tradeoffs: "Segmentation gives the most clinically actionable output (extent, volume) but is the most expensive to annotate and evaluate.",
        practicalUse: "Directly mirrors the three tracks: classification (chest X-ray), segmentation (brain MRI), detection (CT lesion).",
        status: "implemented",
      },
      {
        id: "imaging-metrics",
        title: "Dice, IoU, sensitivity, specificity, AUROC, AUPRC, F1, PPV & NPV",
        summary: "The standard metric family for imaging tasks: Dice and IoU measure segmentation overlap; sensitivity/specificity and PPV/NPV describe a classifier's error tradeoffs at a threshold; AUROC/AUPRC summarize performance across all thresholds; F1 balances precision and recall.",
        math: "Dice = 2|A∩B| / (|A|+|B|); IoU = |A∩B| / |A∪B|; Sensitivity = TP/(TP+FN); PPV = TP/(TP+FP).",
        tradeoffs: "AUPRC is far more informative than AUROC under class imbalance, since AUROC can look excellent while precision on the rare positive class is poor.",
        practicalUse: "Each track declares a primary and secondary metric set (e.g. AUROC plus AUPRC/sensitivity/specificity for chest X-ray) rendered directly in the overview and training views. For the chest X-ray track specifically, those displayed values are now computed from a real trained model's predictions on held-out PneumoniaMNIST data, not a formula — brain MRI and CT lesion metrics remain display-layer only.",
        status: "implemented",
      },
      {
        id: "domain-shift",
        title: "Scanner variation and domain shift",
        summary: "Different manufacturers, field strengths, and reconstruction kernels produce systematically different pixel statistics for the same anatomy, so a model trained on one scanner population can degrade on another.",
        tradeoffs: "Federated learning across many real sites is partly a defense against domain shift, but non-IID data is the same problem viewed from the optimization side.",
        practicalUse: "Represented conceptually by per-site local AUROC varying around the global figure in the node table; not driven by real scanner metadata.",
        status: "simulated",
      },
      {
        id: "label-quality",
        title: "Label quality and inter-rater agreement",
        summary: "Ground truth in medical imaging comes from expert readers who disagree with each other; inter-rater agreement quantifies how much label noise a dataset inherently has.",
        math: "Cohen's κ = (p_o − p_e) / (1 − p_e), where p_o is observed agreement and p_e is chance agreement.",
        tradeoffs: "A model cannot exceed the reliability of its labels; reported accuracy above inter-rater agreement usually signals evaluation leakage, not superhuman performance.",
        practicalUse: "Not tracked in this console — no annotation pipeline or multi-reader adjudication exists here.",
        status: "reserved",
      },
      {
        id: "deidentification-governance",
        title: "De-identification and dataset governance",
        summary: "De-identification removes or obfuscates direct and indirect identifiers before data can be used for research; dataset governance covers consent, retention, and access-control policy on top of that.",
        security: "De-identification is not guaranteed anonymization — imaging data can still carry re-identifying signal (e.g. facial reconstruction from a CT volume).",
        tradeoffs: "Stronger de-identification can remove clinically or scientifically useful context along with the identifying signal.",
        practicalUse: "Out of scope by design: no patient-level data of any kind is ingested, stored, or shown, so de-identification has nothing to act on here.",
        status: "reserved",
      },
    ],
  },
  {
    id: "federated-learning",
    title: "Federated learning",
    icon: Network,
    intro: "Client updates, aggregation strategy, and the practical limits of training across independent hospitals that never share raw data.",
    concepts: [
      {
        id: "cross-silo-cross-device",
        title: "Cross-silo versus cross-device learning",
        summary: "Cross-silo federations have a small number of reliable, high-compute participants (hospitals); cross-device federations have millions of unreliable, low-compute participants (phones).",
        tradeoffs: "Cross-silo can assume near-full participation and stronger per-participant identity each round; cross-device must assume most clients are offline at any moment and design for that.",
        practicalUse: "This is a cross-silo design: exactly 10 named hospital nodes participate, each individually identifiable and expected to report every round.",
        status: "implemented",
      },
      {
        id: "coordinator-clients",
        title: "Central coordinator and client nodes",
        summary: "The coordinator holds the global model, selects participants, distributes weights, and aggregates returned updates; clients hold local data and never send it anywhere.",
        security: "Centralizing coordination is operationally simple but makes the coordinator a single point of failure and a natural attack target — see the privacy & security module.",
        tradeoffs: "A single coordinator simplifies orchestration logic at the cost of that concentration of trust and failure risk.",
        practicalUse: "The API server plays the coordinator role: it owns round state, node roster, and the aggregation-derived metrics the dashboard reads.",
        status: "implemented",
      },
      {
        id: "local-training-sgd",
        title: "Local training and local SGD",
        summary: "Each client runs several steps of stochastic gradient descent on its own data before sending an update, rather than sending a gradient after every single sample.",
        math: "Local update after E epochs: θ_i^(t+1) = θ_i^(t) − η·Σ_(e=1..E) ∇L(θ; batch_e).",
        tradeoffs: "More local steps reduce the communication rounds needed but push local models further apart before averaging, the root cause of client drift.",
        practicalUse: "For the chest X-ray track, this now runs for real: 3 of the track's 10 simulated hospital clients each execute real local SGD steps (plain PyTorch, not Flower — see the FedAvg entry) on their own Dirichlet-partitioned shard of PneumoniaMNIST before contributing to the average. The other 7 chest-xray sites, and every site on brain MRI and CT lesion, still just show an 'update receipt' with no real local training.",
        status: "simulated",
      },
      {
        id: "fedavg",
        title: "FedAvg",
        summary: "The baseline federated algorithm: clients train locally, then the coordinator averages their weights weighted by local sample count.",
        math: "θ^(t+1) = Σ_i (n_i / N)·θ_i^(t+1), where n_i is client i's sample count and N is the total.",
        tradeoffs: "Simple and effective under roughly IID data, but degrades as client data distributions diverge.",
        practicalUse: "Implemented for real on the chest X-ray track: a direct PyTorch FedAvg implementation (ml/federation-engine — Flower/Ray's simulation overhead proved unworkable on this setup and was dropped for a plain training loop) runs FedAvg for real over 8 rounds across 3 of the track's 10 simulated hospital clients, aggregating actual local SGD updates weighted by client sample count, in about 19 seconds end to end. FedProx and FedOpt remain simulated, label-only aggregation methods for the brain MRI and CT lesion tracks respectively.",
        status: "implemented",
      },
      {
        id: "fedprox",
        title: "FedProx",
        summary: "Adds a proximal term to each client's local loss that penalizes drifting too far from the global model, stabilizing training under heterogeneous data and partial local work.",
        math: "Local objective: minimize L_i(θ) + (μ/2)·‖θ − θ^(t)‖².",
        tradeoffs: "The proximal coefficient μ trades local adaptation for global stability; a poorly tuned μ can slow convergence without meaningfully helping heterogeneity.",
        practicalUse: "Named as the aggregation method for the brain MRI track, reflecting that segmentation labels vary more across sites than classification labels.",
        status: "simulated",
      },
      {
        id: "fedopt",
        title: "FedOpt",
        summary: "Treats the aggregated client update as a pseudo-gradient and applies a server-side adaptive optimizer (e.g. Adam) on top of it, rather than plain averaging.",
        math: "Server update: θ^(t+1) = ServerOpt(θ^(t), Δ^(t)), where Δ^(t) is the aggregated client delta.",
        tradeoffs: "Server-side adaptivity can accelerate convergence and dampen noisy updates, at the cost of extra server state (momentum, variance) to manage.",
        practicalUse: "Named as the aggregation method for the CT lesion track, where update noise from a harder detection task benefits most from adaptive optimization.",
        status: "simulated",
      },
      {
        id: "client-sampling",
        title: "Client sampling",
        summary: "Selecting a subset of clients to participate in a given round, rather than requiring all of them, to control round latency and cost.",
        tradeoffs: "Sampling too few clients per round increases variance in the aggregated update; sampling all of them removes that variance but caps round speed at the slowest required participant.",
        practicalUse: "This console requires no sampling decision — all 10 sites are eligible every round, consistent with a cross-silo design.",
        status: "implemented",
      },
      {
        id: "non-iid-data",
        title: "Non-IID data",
        summary: "Client datasets differ systematically in label distribution, feature distribution, or both — the near-universal case for real hospitals, which differ in patient population, equipment, and protocol.",
        tradeoffs: "Non-IID data is the primary reason federated accuracy can lag centralized training on the same total data; the fix is architectural (FedProx, personalization), not just more rounds.",
        practicalUse: "For the chest X-ray track, this is now real for 3 of its 10 sites: each gets a Dirichlet label-skew partition of PneumoniaMNIST, producing genuinely different local label distributions per site (one real run split 271-2906 samples per client, with class balance ranging from 15% to 96% pneumonia). The other 7 chest-xray sites, and all of brain MRI and CT lesion, still only represent this indirectly, by giving each site a different local AUROC around the global figure with no real underlying data distribution driving it.",
        status: "simulated",
      },
      {
        id: "heterogeneity",
        title: "Statistical and system heterogeneity",
        summary: "Statistical heterogeneity is differing data distributions across clients; system heterogeneity is differing compute, bandwidth, and reliability across clients.",
        tradeoffs: "A federation has to design for the slowest, least reliable client at the same time as the most divergent data distribution — the two compound.",
        practicalUse: "One node is deliberately shown in an 'attention' state and another in 'syncing' to represent both forms without simulating a real cause.",
        status: "simulated",
      },
      {
        id: "client-drift",
        title: "Client drift",
        summary: "Under non-IID data and multiple local steps, local models converge toward each site's own optimum before averaging, pulling the aggregated model away from the true global optimum.",
        tradeoffs: "More local computation per round reduces communication cost but increases drift; FedProx's proximal term directly trades off against this.",
        practicalUse: "The Federation Agent's seeded assessment ('Site 04 shows elevated validation loss') is a stand-in for what real drift-detection output would look like.",
        status: "simulated",
      },
      {
        id: "stragglers",
        title: "Stragglers and unavailable clients",
        summary: "A straggler is a client that responds much slower than the rest; an unavailable client drops out of a round entirely, whether from a network fault, a crash, or scheduled maintenance.",
        tradeoffs: "Waiting for every client maximizes data usage per round but caps round latency at the worst-case client; proceeding without them is faster but biases the update toward whoever stayed online.",
        practicalUse: "The overview's '8/10 sites online' figure is the visible symptom of this concept; there is no real timeout or retry logic behind it.",
        status: "simulated",
      },
      {
        id: "partial-participation",
        title: "Partial participation",
        summary: "Aggregating from whichever subset of selected clients actually responds within the round window, instead of blocking on full participation.",
        tradeoffs: "Keeps the federation moving despite stragglers, but the aggregated update is not guaranteed to be an unbiased estimate of what full participation would have produced.",
        practicalUse: "Round 12 in this console is explicitly described as aggregating updates from 8 of 10 sites.",
        status: "implemented",
      },
      {
        id: "async-fl",
        title: "Asynchronous federated learning",
        summary: "Clients send updates whenever they finish local training rather than waiting for a synchronized round boundary; the coordinator applies each update as it arrives, usually with a staleness discount.",
        tradeoffs: "Removes the straggler bottleneck entirely, but stale updates computed against an old global model can destabilize convergence if not discounted correctly.",
        practicalUse: "Not used here — this console models synchronous, round-based federation exclusively (round 12, discrete round states).",
        status: "reserved",
      },
      {
        id: "personalization",
        title: "Personalization",
        summary: "Techniques that let each client keep a locally adapted variant of the global model, rather than forcing every site onto one identical model, to better fit local data distribution.",
        tradeoffs: "Personalization can raise every site's local accuracy but complicates evaluation and governance — there is no single model whose safety review covers everyone.",
        practicalUse: "Not implemented; the console reports one global model version per track, shared by every site.",
        status: "reserved",
      },
      {
        id: "global-vs-local-models",
        title: "Global versus local models",
        summary: "The global model is the coordinator's aggregated result; the local model is any individual client's current parameters, which may differ from the global model between rounds.",
        tradeoffs: "Evaluating only the global model can hide sites where the shared model performs badly; evaluating only local models hides whether federation is actually helping versus training alone.",
        practicalUse: "The overview shows global AUROC/accuracy alongside a per-node local AUROC column specifically so both views are visible together.",
        status: "implemented",
      },
      {
        id: "communication-compression",
        title: "Communication compression",
        summary: "Techniques (quantization, sparsification, low-rank updates) that shrink the update sent from client to coordinator, since network bandwidth is often the real bottleneck, not compute.",
        tradeoffs: "Aggressive compression cuts bandwidth and round time but adds approximation error to every update, which compounds over many rounds if not corrected.",
        practicalUse: "Not applicable at this simulated scale — no real payloads are transmitted between the mock client sites and the coordinator.",
        status: "reserved",
      },
      {
        id: "round-convergence-recovery",
        title: "Round convergence and failure recovery",
        summary: "Convergence is judged by whether the global metric is still improving round over round; failure recovery is what happens when a round fails validation — retry, rollback, or hold for review.",
        tradeoffs: "Auto-retrying a failed round risks repeating whatever caused the failure; requiring a human decision is safer but slower — the agent recommendation flow makes this tradeoff explicit.",
        practicalUse: "The agent's recommendation to hold Site 04's update, and the human approve/dismiss action, are this concept's concrete implementation. On the chest X-ray track, that judgment now has a real basis to sit on top of: a completed 8-round direct-PyTorch FedAvg run across 3 of the track's 10 clients, with round-over-round metrics coming from real aggregation rather than a seed-index formula. Failure recovery itself (retry/rollback logic) is still not implemented — the run either completes or it doesn't.",
        status: "implemented",
      },
    ],
  },
  {
    id: "privacy-security",
    title: "Privacy & security",
    icon: LockKeyhole,
    intro: "Threat models, the cryptography and noise mechanisms that defend against them, and the attacks a federation has to assume are possible.",
    concepts: [
      {
        id: "threat-models",
        title: "Threat models",
        summary: "An explicit statement of who the adversary is assumed to be (honest-but-curious coordinator, malicious client, external network attacker) and what they can see or do — every privacy technique only makes sense against a stated threat model.",
        tradeoffs: "Defending against a stronger threat model costs more compute and complexity than defending against an honest-but-curious one; over-specifying wastes engineering effort, under-specifying leaves real gaps.",
        practicalUse: "This console documents its assumed threat model explicitly: the coordinator is trusted with aggregate metrics only, never with raw imaging or patient identifiers.",
        status: "implemented",
      },
      {
        id: "secure-aggregation",
        title: "Secure aggregation",
        summary: "A cryptographic protocol where the coordinator learns only the sum (or average) of client updates, never any individual client's update, typically via pairwise masking that cancels out on summation.",
        math: "Each client sends x_i + Σ_j s_(i,j) (masks that cancel across all clients); the coordinator recovers Σ x_i without ever seeing an individual x_i.",
        security: "Guarantees strong per-client confidentiality but requires enough participating clients for the masks to cancel.",
        tradeoffs: "Adds a key-setup communication round and requires a minimum participant threshold to hold the guarantee.",
        practicalUse: "Not implemented — the privacy page now says so directly ('Secure aggregation: Not implemented') rather than implying it's an enforced control. Differential privacy (see that entry) is real in this console; secure aggregation is a separate, still-unimplemented technique.",
        status: "reserved",
      },
      {
        id: "differential-privacy",
        title: "Differential privacy",
        summary: "A formal guarantee that the presence or absence of any single training example changes the output distribution by at most a bounded amount, so an observer cannot confidently tell whether a specific record was included.",
        math: "Pr[M(D) ∈ S] ≤ e^ε · Pr[M(D′) ∈ S] + δ, for any datasets D, D′ differing in one record.",
        tradeoffs: "Smaller ε gives a stronger guarantee but adds more noise, degrading model accuracy — every DP deployment is a negotiated point on this privacy/utility curve.",
        practicalUse: "Real, via DP-SGD (Opacus) in ml/federation-engine — not a display placeholder. Each client's local training uses real per-example gradient clipping plus calibrated Gaussian noise, and the epsilon shown throughout this console (network overview, per-node privacy status, training rounds) is computed by a real RDP accountant over the actual training that happened, not chosen to look good. Verified live: one real run at noise_multiplier=0.5/max_grad_norm=5.0 produced ε≈29 after 8 rounds and a measured accuracy drop (0.740 AUROC vs. 0.921 without DP) — a real, reported privacy/utility tradeoff, not a hidden one. This is local per-client DP-SGD, not a formal centrally-coordinated guarantee across the whole federation; see 'Noise mechanisms and privacy budgets' for what the network-level number means.",
        status: "implemented",
      },
      {
        id: "gradient-clipping",
        title: "Gradient clipping",
        summary: "Rescaling each client's update so its norm never exceeds a fixed bound — the prerequisite step that makes differential privacy's noise-to-signal ratio calculable and bounds any single client's influence on the aggregate.",
        math: "g̃ = g · min(1, C / ‖g‖), where C is the clipping norm.",
        tradeoffs: "A small clipping bound strengthens the privacy guarantee and limits outlier influence but can suppress a legitimately large, informative update from a site with a real distribution shift. Observed directly here: clipping to C=1.0 collapsed the model into always predicting the majority class; loosening to C=5.0 let it actually learn, at the cost of a larger (weaker) epsilon.",
        practicalUse: "Real per-example clipping via Opacus, applied to every client's local gradients before noise is added — see ml/federation-engine/train_utils.py's train_with_dp.",
        status: "implemented",
      },
      {
        id: "noise-privacy-budget",
        title: "Noise mechanisms and privacy budgets",
        summary: "Calibrated random noise (typically Gaussian or Laplace) is added to a clipped update to achieve a target ε; the privacy budget tracks how much ε has been spent across all rounds so far, since privacy loss accumulates.",
        math: "Gaussian mechanism: add noise ~ N(0, σ²C²), where σ scales with C/ε; cumulative privacy loss composes across rounds.",
        tradeoffs: "A fixed lifetime budget forces a choice between running more rounds or spending more budget per round — both cannot be maximized at once.",
        practicalUse: "Real Gaussian-mechanism noise via Opacus. Each hospital node gets its own PrivacyEngine that persists across all training rounds, so its reported epsilon reflects total privacy actually spent over the whole run, not just the last round — a real, observable signature of this is the per-round epsilon strictly growing round over round (see the training page). The network-wide privacy budget shown is the maximum (weakest) epsilon across clients, since a federation's real guarantee is only as strong as its least private participant, not an average.",
        status: "implemented",
      },
      {
        id: "renyi-dp",
        title: "Rényi differential privacy",
        summary: "An accounting method that composes privacy loss across many rounds far more tightly than naive composition, then converts back to standard (ε, δ)-DP at the end — what makes multi-round DP training practical rather than exhausting the budget in a handful of rounds.",
        math: "Rényi divergence of order α bounds privacy loss per step; total loss composes additively in Rényi space before conversion back to (ε, δ).",
        tradeoffs: "Tighter accounting lets a federation run many more rounds within the same overall budget, but the accounting itself is mathematically involved and easy to implement incorrectly.",
        practicalUse: "Real — this is exactly what Opacus's accountant does under the hood to produce every epsilon figure in this console; not a separately implemented feature, but the actual mechanism the 'Differential privacy' and 'Noise mechanisms' entries above rely on.",
        status: "implemented",
      },
      {
        id: "membership-inference",
        title: "Membership inference",
        summary: "An attack that tries to determine whether a specific record was in a model's training set, typically by exploiting the fact that models are more confident on data they memorized.",
        security: "Differential privacy directly bounds this attack's success rate; models trained without any privacy mechanism have no such guarantee, even if no attack has been demonstrated against them yet.",
        tradeoffs: "Defending against it costs the same privacy/utility tradeoff as differential privacy generally.",
        practicalUse: "Documented as a threat this design is meant to resist, but no attack simulation or defense evaluation runs in this console.",
        status: "reserved",
      },
      {
        id: "model-inversion",
        title: "Model inversion",
        summary: "An attack that reconstructs an approximation of training inputs from a model's outputs or gradients.",
        security: "Sending full gradients (rather than an aggregated, clipped, or compressed update) increases inversion risk — one concrete reason federated learning sends model updates, not raw data, but updates alone are not automatically safe.",
        tradeoffs: "Mitigations (aggregation, clipping, noise) all cost model utility to reduce this risk.",
        practicalUse: "Documented as the reason raw imaging never leaves a site, even in update form; no reconstruction attack is simulated.",
        status: "reserved",
      },
      {
        id: "gradient-leakage",
        title: "Gradient leakage",
        summary: "A stronger, empirically demonstrated version of model inversion showing raw gradients (before aggregation) can leak near-exact training images in some settings — a key argument for aggregating before the coordinator ever inspects an update.",
        security: "Secure aggregation directly closes this attack surface for the coordinator; without it, 'the coordinator never gets your data' is only true for raw pixels, not necessarily for gradients derived from them.",
        tradeoffs: "Closing this gap requires the secure-aggregation infrastructure, which this console does not implement.",
        practicalUse: "The stated design invariant that raw imaging never leaves the originating site implicitly depends on this concept, but no gradient-level protection is implemented or demonstrated.",
        status: "reserved",
      },
      {
        id: "byzantine-clients",
        title: "Byzantine clients",
        summary: "A client that sends an arbitrary, potentially adversarial update instead of an honest local training result — from a simple software bug to a deliberate attempt to corrupt the global model.",
        security: "Robust aggregation rules (coordinate-wise median, trimmed mean) resist Byzantine clients but sacrifice some statistical efficiency compared to plain averaging under honest participants.",
        tradeoffs: "Robust aggregation is more compute-intensive and can discard legitimate outlier signal along with attacks.",
        practicalUse: "The 'Site 04' scenario is framed as a data-quality issue rather than malicious behavior; no Byzantine-robust aggregation rule is implemented.",
        status: "reserved",
      },
      {
        id: "data-poisoning",
        title: "Data poisoning",
        summary: "An attack where a malicious client manipulates its own local training data so its resulting update degrades the global model's accuracy, either broadly or on a specific target input.",
        security: "Detecting poisoning usually means scrutinizing update statistics for outliers, trading some client privacy for federation integrity.",
        tradeoffs: "Any outlier-detection defense risks false positives against legitimate but unusual local data distributions.",
        practicalUse: "Not simulated; the elevated-loss scenario in this console is framed as a benign local data-quality problem, not an attack.",
        status: "reserved",
      },
      {
        id: "backdoor-attacks",
        title: "Backdoor attacks",
        summary: "A targeted form of data poisoning where a client trains the model to behave normally except on inputs containing a specific trigger pattern, which then causes a chosen misclassification.",
        security: "Backdoors are hard to detect precisely because the model performs normally on all standard validation data — only trigger-aware testing surfaces them.",
        tradeoffs: "Trigger-aware testing adds evaluation cost for a class of attack that may never be observed.",
        practicalUse: "Not simulated or defended against in this console.",
        status: "reserved",
      },
      {
        id: "sybil-attacks",
        title: "Sybil attacks",
        summary: "An adversary creates or controls many fake client identities to gain disproportionate influence over aggregation, or to defeat a minimum-participant secure-aggregation threshold.",
        security: "Strong client identity and enrollment is the main defense; the harder a hospital node is to fake or duplicate, the less exposed the federation is to this attack.",
        tradeoffs: "Strict enrollment controls add onboarding friction for legitimate new sites.",
        practicalUse: "Real, but scoped: POST /network/inference requires each hospital's actual per-node API key (a random secret, issued once, only its SHA-256 hash ever stored) before an upload can be attributed to that site — a caller cannot claim to be a hospital it doesn't hold the credential for. This covers the one real network boundary that exists today. It does not cover the training pipeline itself, which still runs as a single simulated process with no real multi-party network protocol, and it is an API key, not mTLS or a PKI — see 'TLS, mTLS, key rotation & audit trails' for what's still missing.",
        status: "simulated",
      },
      {
        id: "homomorphic-encryption",
        title: "Homomorphic encryption",
        summary: "Encryption that allows specific computations (e.g. addition) to be performed directly on ciphertexts, producing an encrypted result that decrypts to the correct answer — letting the coordinator sum encrypted updates without ever holding the decryption key.",
        security: "Gives the strongest confidentiality guarantee for aggregation among the options considered here.",
        tradeoffs: "Even partially homomorphic schemes carry substantial compute and bandwidth overhead compared to secure aggregation's masking approach.",
        practicalUse: "Documented as an available production-grade alternative or complement to secure aggregation; not evaluated or deployed here. Advanced cryptography like this is represented in the architecture but must be independently validated before being called production-enabled.",
        status: "reserved",
      },
      {
        id: "secure-multiparty-computation",
        title: "Secure multiparty computation",
        summary: "A family of protocols letting multiple parties jointly compute a function over their private inputs while revealing only the output, generalizing beyond the simple sum that secure aggregation targets.",
        tradeoffs: "More flexible than secure aggregation or homomorphic encryption alone, but typically the most expensive option in both compute and communication rounds.",
        practicalUse: "Documented as a possible future primitive for richer joint computations than sum-based aggregation; not implemented.",
        status: "reserved",
      },
      {
        id: "trusted-execution-environments",
        title: "Trusted execution environments",
        summary: "Hardware-isolated enclaves (e.g. Intel SGX, AMD SEV, Azure confidential computing) that let code run and data be processed with confidentiality and integrity guarantees even if the host operating system is compromised.",
        security: "TEEs move trust from cryptographic proofs to the hardware vendor and enclave implementation, and have had real side-channel vulnerabilities — an operational tradeoff, not a strictly stronger guarantee than well-implemented cryptography.",
        tradeoffs: "Lower runtime overhead than most cryptographic alternatives, in exchange for hardware trust assumptions.",
        practicalUse: "Documented as an Azure confidential-computing option for hosting the coordinator in production; not used in this console.",
        status: "reserved",
      },
      {
        id: "tls-mtls-key-rotation-audit",
        title: "TLS, mTLS, key rotation & audit trails",
        summary: "TLS encrypts traffic and authenticates the server; mTLS additionally authenticates the client, which matters when clients are hospital systems, not anonymous browsers; key rotation limits the blast radius of a leaked credential; audit trails make every privileged action reviewable after the fact.",
        tradeoffs: "mTLS and short-lived rotated credentials add real operational overhead (certificate issuance, renewal automation) in exchange for meaningfully reducing the impact of a single compromised secret.",
        practicalUse: "The event log and audit ledger implement the audit-trail half of this concept today, and per-node API keys (see 'Sybil attacks') give the inference endpoint real client credential checking. Transport-level mTLS, certificate-based identity, and key rotation are still documented as production requirements, not implemented in this console.",
        status: "simulated",
      },
    ],
  },
  {
    id: "evaluation-fairness",
    title: "Evaluation & responsible AI",
    icon: ShieldCheck,
    intro: "How to read a metric honestly: at what granularity, with what uncertainty, across which subgroups, and how far it is from clinical validation.",
    concepts: [
      {
        id: "global-vs-site-eval",
        title: "Global versus site-level evaluation",
        summary: "Global evaluation measures the aggregated model against a pooled or federated held-out set; site-level evaluation measures the same model separately at each site, which can reveal large disparities a single global number hides.",
        tradeoffs: "Reporting only the global metric is simpler but can mask a model that works well everywhere except one systematically under-served site.",
        practicalUse: "The overview shows global AUROC/accuracy; the training and node views show per-site local AUROC side by side specifically so this gap is visible.",
        status: "implemented",
      },
      {
        id: "cross-site-generalization",
        title: "Cross-site generalization",
        summary: "How well a model trained on some sites' data performs on a site whose data it never saw — the imaging analogue of out-of-distribution generalization, driven by domain shift.",
        tradeoffs: "A federation with strong cross-site generalization is more valuable but harder to achieve than one merely fitting the specific participating sites well.",
        practicalUse: "Not separately measured here; the per-track global metric implicitly averages over exactly the sites that contributed, not held-out sites.",
        status: "reserved",
      },
      {
        id: "confidence-intervals-significance",
        title: "Confidence intervals and statistical significance",
        summary: "A point estimate like 'AUROC = 0.91' is incomplete without a confidence interval showing the range consistent with the observed data, and a significance test before concluding one round or model actually outperforms another.",
        math: "A common approach for AUROC is bootstrap resampling of the evaluation set to build an empirical confidence interval.",
        tradeoffs: "Skipping interval estimation makes round-over-round metric changes look more meaningful than the underlying sample size supports.",
        practicalUse: "The training view shows a single point figure ('+0.014 vs round 17') with no interval; this is flagged in the console's own disclaimers as telemetry, not a statistical claim.",
        status: "reserved",
      },
      {
        id: "subgroup-performance",
        title: "Subgroup performance",
        summary: "Breaking down a metric by demographic or clinical subgroup (age, sex, scanner type, disease severity) instead of reporting only an aggregate, since aggregate performance can conceal poor performance on a minority subgroup.",
        tradeoffs: "Subgroup analysis requires subgroup labels, which carry privacy sensitivity and may not exist at the granularity a rigorous breakdown needs.",
        practicalUse: "Not implemented; this console has no patient-level or demographic data to subgroup by design.",
        status: "reserved",
      },
      {
        id: "fairness-institutions-demographics",
        title: "Fairness across institutions and demographics",
        summary: "In a federated hospital network, fairness has two layers: whether the shared model treats patient demographics equitably, and whether it treats participating institutions equitably (a small or lower-resourced site isn't systematically worse served).",
        tradeoffs: "Optimizing purely for average global accuracy can implicitly favor sites that contribute the most data, at the expense of smaller sites.",
        practicalUse: "The node table's data-volume column makes contribution imbalance visible, but no fairness metric is computed from it. This is the concept F9 coverage-visibility work would eventually build on.",
        status: "reserved",
      },
      {
        id: "calibration-curves",
        title: "Calibration curves",
        summary: "A plot of predicted probability against observed frequency across bins — the visual counterpart to the scalar Expected Calibration Error, useful for spotting whether a model is over- or under-confident in specific probability ranges.",
        tradeoffs: "A single ECE number can hide a model that's well-calibrated in most ranges but dangerously overconfident in the high-risk range that matters clinically.",
        practicalUse: "Not plotted; only a static scalar calibration figure appears in the training view.",
        status: "reserved",
      },
      {
        id: "error-analysis",
        title: "Error analysis",
        summary: "Systematically examining a model's specific failure cases (false positives, false negatives, near-misses) to find patterns rather than relying on summary metrics alone.",
        tradeoffs: "Rigorous error analysis takes real clinical review time but is often what actually finds a failure mode, since aggregate metrics by construction average failures away.",
        practicalUse: "Not implemented — no case-level output exists in this console to analyze.",
        status: "reserved",
      },
      {
        id: "drift",
        title: "Data drift and concept drift",
        summary: "Data drift is a change in the input distribution over time (new scanner, new patient population); concept drift is a change in the relationship between inputs and the true label — both silently degrade a deployed model.",
        tradeoffs: "Monitoring for drift costs ongoing evaluation infrastructure, but not monitoring means a model can degrade in production a long time before anyone notices from complaints alone.",
        practicalUse: "The Federation Agent's role is explicitly framed around this concept ('detect unusual site performance or data drift'), but the current implementation surfaces one seeded scenario, not a live drift detector.",
        status: "simulated",
      },
      {
        id: "reproducibility",
        title: "Reproducibility",
        summary: "The ability to rerun a training or evaluation process and get the same (or statistically equivalent) result, which requires fixing or recording every source of nondeterminism: data version, code version, config, and random seed.",
        tradeoffs: "Full reproducibility adds engineering overhead but is what makes a reported result trustworthy and debuggable rather than a one-off artifact.",
        practicalUse: "Documented as an MLOps requirement; no training runs exist yet in this console to reproduce.",
        status: "reserved",
      },
      {
        id: "model-cards",
        title: "Model cards",
        summary: "A standardized document accompanying a model describing its intended use, training data characteristics, evaluation results (including subgroup breakdowns), and known limitations.",
        tradeoffs: "Model cards take time to write and keep current, but are what lets a downstream user evaluate fitness for purpose without re-deriving it from raw metrics.",
        practicalUse: "The Academy's per-track description (task, model, primary/secondary metrics) is a minimal precursor to a real model card; it lacks limitations, training-data description, and subgroup results.",
        status: "simulated",
      },
      {
        id: "dataset-cards",
        title: "Dataset cards",
        summary: "The dataset-side counterpart to a model card: provenance, collection protocol, inclusion/exclusion criteria, known biases, and the consent or governance basis for a training or evaluation dataset.",
        tradeoffs: "Without a dataset card, a model's reported performance can't be properly contextualized — the same AUROC means something different on a broad dataset versus a narrow, single-site one.",
        practicalUse: "Not present — no real dataset exists behind any track in this console.",
        status: "reserved",
      },
      {
        id: "clinical-validation-boundaries",
        title: "Clinical validation boundaries",
        summary: "The formal process (prospective studies, regulatory review, real-world deployment monitoring) required before a research model can be used to inform actual patient care — a categorically different bar than a strong retrospective metric.",
        tradeoffs: "Skipping this boundary to deploy a research model directly is the single most consequential failure mode this platform is designed to prevent, at the cost of the platform necessarily doing less than a clinical tool.",
        practicalUse: "Enforced as a standing disclaimer on every page in this console: research telemetry only, not a diagnostic device or clinical decision support system.",
        status: "implemented",
      },
      {
        id: "research-vs-clinical-metrics",
        title: "Why research metrics are not clinical approval",
        summary: "A strong AUROC on a retrospective, curated evaluation set says a model can discriminate classes on that data — it does not establish that the model helps patient outcomes prospectively, integrates safely into a clinical workflow, or generalizes beyond its evaluation cohort.",
        tradeoffs: "Treating a good research metric as clinical validation skips exactly the steps that catch generalization failure and workflow harms before they reach a patient.",
        practicalUse: "This is the explicit rationale printed alongside every metric surface in this console (overview, training, academy).",
        status: "implemented",
      },
    ],
  },
  {
    id: "mlops",
    title: "MLOps & experiment management",
    icon: Database,
    intro: "The operational spine that makes a model version traceable, monitorable, and safe to roll back — independent of whether it happens to work today.",
    concepts: [
      {
        id: "experiment-lineage",
        title: "Experiment lineage",
        summary: "A recorded chain connecting a model version back to the exact code, config, data version, and hyperparameters that produced it, so any result can be traced to its cause.",
        tradeoffs: "Lineage tracking has real storage and tooling cost, but without it a model's 'why did this change' question becomes unanswerable within a few weeks.",
        practicalUse: "The event log attaches a round number and model version to relevant events, a minimal lineage thread; it doesn't capture code or config versions.",
        status: "simulated",
      },
      {
        id: "dataset-model-versioning",
        title: "Dataset and model versioning",
        summary: "Treating both datasets and trained models as versioned artifacts with immutable identifiers, so 'which data produced this model' is always answerable, and a model can be rolled back to a known-good version.",
        tradeoffs: "Versioning datasets is often skipped because storing multiple large dataset snapshots is expensive, but skipping it breaks reproducibility the moment source data is corrected or expanded.",
        practicalUse: "Model versions are shown as a string per track (e.g. cxr-v0.12); no dataset versioning identifier exists.",
        status: "simulated",
      },
      {
        id: "reproducible-configs",
        title: "Reproducible training configurations",
        summary: "Capturing the full configuration (architecture, hyperparameters, seed, environment) needed to relaunch a training run identically, usually as a single versioned config file rather than scattered flags.",
        tradeoffs: "Config-as-code adds initial setup discipline but eliminates the far more common failure of an undocumented one-off flag change silently affecting a reported result.",
        practicalUse: "Not implemented — no training run exists to configure in this console.",
        status: "reserved",
      },
      {
        id: "model-registry",
        title: "Model registry",
        summary: "A central catalog of every trained model version, its metrics, its lineage, and its deployment stage (staging, production, archived), typically the system a real deployment promotes a model through.",
        tradeoffs: "A registry adds process overhead compared to pushing a new model directly, but is what prevents an unvetted model from silently reaching production.",
        practicalUse: "Documented as the MLflow-compatible target in the proposed stack; not implemented — model version is a display string only.",
        status: "reserved",
      },
      {
        id: "checkpoints",
        title: "Checkpoints",
        summary: "Periodic snapshots of model weights (and optimizer state) saved during training, so a run can resume after interruption or a specific earlier point can be recovered.",
        tradeoffs: "Frequent checkpointing costs storage and I/O time but is the only defense against losing a long training run to a crash.",
        practicalUse: "Not implemented — no training loop runs to checkpoint.",
        status: "reserved",
      },
      {
        id: "rollbacks",
        title: "Rollbacks",
        summary: "Reverting a deployed model to a previously validated version when a newer version underperforms or fails in production, ideally as a fast, low-risk operation rather than an emergency scramble.",
        tradeoffs: "Rollback capability requires keeping prior versions deployable and serving-compatible, an ongoing maintenance cost paid for the ability to fail safely.",
        practicalUse: "The agent's 'hold this update' recommendation is a pre-aggregation analogue of a rollback — refusing a bad update before it becomes the new global model, rather than deploying then reverting.",
        status: "simulated",
      },
      {
        id: "monitoring",
        title: "Monitoring",
        summary: "Continuously tracking a deployed system's health signals (latency, error rate, resource usage) and model-specific signals (prediction distribution, metric trends) to catch problems as they happen.",
        tradeoffs: "Comprehensive monitoring has real cost in storage and alert-fatigue risk if thresholds are too sensitive; too little means problems surface only when a user complains.",
        practicalUse: "The live event stream and per-node status indicators are the operational monitoring surface for this console.",
        status: "implemented",
      },
      {
        id: "drift-detection",
        title: "Drift detection",
        summary: "Automated statistical tests comparing recent production inputs or outputs against a reference distribution to flag data or concept drift before it silently degrades performance.",
        tradeoffs: "Automated drift detection can generate false alarms on natural seasonal or population variation, so thresholds need tuning against real operational history that doesn't yet exist for a new federation.",
        practicalUse: "Represented only as the agent's single seeded 'elevated validation loss' scenario; there's no statistical test running behind it.",
        status: "simulated",
      },
      {
        id: "canary-evaluation",
        title: "Canary evaluation",
        summary: "Rolling out a new model version to a small slice of traffic or a subset of sites first, and only promoting it fully once it clears the canary bar, to limit the blast radius of a bad model.",
        tradeoffs: "Canary rollouts add release-process complexity and delay full rollout, in exchange for catching a regression before it affects the whole federation.",
        practicalUse: "Not implemented; every update that clears validation in this console is treated as applying federation-wide immediately.",
        status: "reserved",
      },
      {
        id: "human-approval-gates",
        title: "Human approval gates",
        summary: "A required human decision point before a consequential automated action (deploying a model, aggregating a flagged update, changing a privacy policy) takes effect.",
        tradeoffs: "Approval gates slow down operations compared to full automation — precisely the tradeoff this platform makes deliberately for any action affecting training, privacy, model versions, or site participation.",
        practicalUse: "The Agent page's approve/dismiss action is a fully implemented human approval gate: the recommendation has no effect on system state until a human resolves it.",
        status: "implemented",
      },
      {
        id: "incident-response",
        title: "Incident response",
        summary: "A defined process for what happens when something goes wrong in production — detection, triage, containment, remediation, and a post-incident review — rather than ad hoc firefighting.",
        tradeoffs: "A formal process has overhead to maintain and rehearse, but is what prevents a real incident from being handled inconsistently under pressure.",
        practicalUse: "Not implemented as a workflow; privacy-threshold and drift events are logged and surfaced but no response runbook exists in this console.",
        status: "reserved",
      },
      {
        id: "auditability",
        title: "Auditability",
        summary: "The property that every consequential action in the system — human or automated — is recorded with who did it, why, and what evidence supported it, in a form that can be reviewed after the fact.",
        tradeoffs: "Comprehensive audit logging has storage and engineering cost, but it's a hard requirement, not a nice-to-have, for a system touching hospital data governance and AI-driven recommendations.",
        practicalUse: "The event log, the privacy audit ledger, and the recorded approve/dismiss decision on every agent recommendation together implement this end to end for the actions this console supports.",
        status: "implemented",
      },
    ],
  },
  {
    id: "agent-governance",
    title: "AI Federation Agent",
    icon: Bot,
    intro: "How the agent is bounded so it explains and evaluates the federation without ever pretending a recommendation is medical truth.",
    concepts: [
      {
        id: "observe-recommend-execute",
        title: "Observation versus recommendation versus execution",
        summary: "Three escalating levels of agent authority: reading logs and reporting only; proposing an action without the power to take it; and taking a bounded action after a required human approval.",
        tradeoffs: "Higher authority increases the agent's usefulness and speed but also the blast radius of a wrong or manipulated recommendation — this platform deliberately starts at 'recommend,' not 'execute unattended.'",
        practicalUse: "The Federation Agent operates strictly at the recommend level: it proposes holding a site's update but cannot hold it itself — only a human approve click does.",
        status: "implemented",
      },
      {
        id: "tool-use-permissions",
        title: "Tool use and action permissions",
        summary: "Which specific system actions an agent is technically capable of invoking (read a metric, flag a site, pause a round) and under what authorization, distinct from what it merely talks about being able to do.",
        security: "Narrowly scoped tool permissions limit what a compromised or malfunctioning agent can do, at the cost of requiring a human for anything outside that narrow set.",
        tradeoffs: "Broader permissions would let the agent act faster but widen the failure surface if a recommendation is wrong.",
        practicalUse: "The agent (a real tool-use loop in artifacts/api-server/src/lib/agent.ts, running against an OpenAI-compatible model) can only call three read-only query tools (overview, nodes, recent events) and one submit_assessment tool; the endpoint that actually records a human decision is only reachable by the approve/dismiss UI, never by the agent itself.",
        status: "implemented",
      },
      {
        id: "evidence-grounded-reasoning",
        title: "Evidence-grounded reasoning",
        summary: "Requiring every agent claim or recommendation to cite the specific metrics, logs, or events it's based on, rather than presenting a conclusion with no traceable support.",
        tradeoffs: "Evidence-grounding constrains an agent to only claim what its actual inputs support — less impressive-sounding than an unconstrained answer, but far more trustworthy for an operational decision.",
        practicalUse: "Real: the agent calls get_network_overview/get_client_nodes/get_recent_events against the live Postgres data before it may submit an assessment, and its system prompt explicitly forbids citing anything a tool did not return.",
        status: "implemented",
      },
      {
        id: "confidence-scoring",
        title: "Confidence scoring",
        summary: "A number representing how certain the agent is in its own assessment, distinct from a model's prediction confidence — this is confidence in a recommendation about the system, not a clinical prediction.",
        tradeoffs: "A single scalar confidence is easy to display but can create false precision; it should read as a rough signal that invites scrutiny, not a rigorously calibrated probability.",
        practicalUse: "Rendered directly on the Agent page as a percentage with a visual ring, alongside the disclaimer that this is a bounded recommendation, not a certainty.",
        status: "implemented",
      },
      {
        id: "risk-scoring",
        title: "Risk scoring",
        summary: "A categorical or numeric estimate of what could go wrong if a recommendation is followed (or not followed) — privacy risk, model-quality risk, operational risk, or governance risk.",
        tradeoffs: "Coarse risk categories (Low/Moderate/High) are easy to scan quickly but compress nuance a full risk analysis would separate out.",
        practicalUse: "Every assessment shows a Risk field ('Moderate') alongside Impact and Confidence in the agent telemetry panel.",
        status: "implemented",
      },
      {
        id: "expected-vs-observed-value",
        title: "Expected versus observed value",
        summary: "Expected value is what the agent predicted an action would achieve before it was taken; observed value is what actually happened afterward — comparing the two is how an agent's track record, not just its rhetoric, gets evaluated over time.",
        tradeoffs: "Tracking observed value requires following up after a decision, more work than issuing a recommendation and moving on, but it's the only way to tell whether the agent is actually calibrated.",
        practicalUse: "The agent now writes a genuine Expected value when it generates an assessment; the Observed value recorded on resolution is still a template sentence rather than a measurement from a real subsequent training round, since there is no real training loop yet to observe an outcome from.",
        status: "simulated",
      },
      {
        id: "action-value-cards",
        title: "Action Value Cards",
        summary: "The structured record for every significant agent action — Action, Purpose, Evidence, Expected value, Observed value, Risk, Confidence, Human decision, Outcome — designed so a recommendation is auditable like a financial transaction, not just a chat message.",
        tradeoffs: "A full nine-field card is more overhead to populate than a plain recommendation, but is what turns 'the AI suggested something' into a reviewable governance record.",
        practicalUse: "The Agent page renders the full structure — purpose, evidence, expected value, observed value (filled in on resolution), confidence, impact/risk, human decision, and outcome — and keeps a history panel of past resolved cards per track.",
        status: "implemented",
      },
      {
        id: "human-approval",
        title: "Human approval",
        summary: "The required, recorded decision point where a person explicitly accepts or rejects an agent's recommendation before it has any effect on the system.",
        tradeoffs: "Requiring approval on every recommendation doesn't scale to very high recommendation volume, but at this platform's current scale the safety benefit clearly outweighs the throughput cost.",
        practicalUse: "Fully implemented: the approve/dismiss buttons on the Agent page call a resolution endpoint that permanently records the decision and is reflected back into the assessment's status.",
        status: "implemented",
      },
      {
        id: "hallucination-controls",
        title: "Hallucination controls",
        summary: "Constraints that keep an agent from asserting something not actually supported by its inputs — grounding every claim in retrievable evidence, refusing to answer beyond available data, and never inventing patient-level detail it was never given.",
        tradeoffs: "Strict grounding sometimes means the agent must say it lacks enough evidence instead of giving a more satisfying-sounding but unsupported answer — a tradeoff the platform accepts deliberately.",
        practicalUse: "Enforced structurally: the agent's only inputs are its three read-only query tools' real return values, and its system prompt explicitly instructs it to report normal telemetry as normal rather than manufacture a concern.",
        status: "implemented",
      },
      {
        id: "refusal-behavior",
        title: "Refusal behavior",
        summary: "An agent explicitly declining to make a recommendation, or declining to treat a metric as clinical fact, when it lacks sufficient evidence or the question is outside its bounded scope (e.g. a diagnostic judgment about a specific patient).",
        tradeoffs: "An agent that never refuses will eventually overreach into claims it can't support; refusal is a feature of a well-scoped agent, not a failure of it.",
        practicalUse: "The system prompt instructs the agent to produce a low-impact, low-risk assessment when nothing is wrong rather than inventing an issue, and the platform-wide 'not a diagnostic device' boundary still applies; there's no separate dynamic per-query refusal path tested yet.",
        status: "simulated",
      },
      {
        id: "prompt-decision-traceability",
        title: "Prompt and decision traceability",
        summary: "The ability to reconstruct exactly what inputs and reasoning path led an agent to a specific recommendation, which matters for debugging the agent and for governance review after the fact.",
        tradeoffs: "Full traceability has storage and privacy-review overhead of its own, since the trace itself can contain sensitive operational detail.",
        practicalUse: "A real model call and tool-use trace now exists behind every freshly generated assessment (logged via the server's structured logger), but that trace isn't persisted alongside the assessment row for later audit — only the final Action Value Card is stored.",
        status: "simulated",
      },
      {
        id: "agent-recommendation-evaluation",
        title: "Evaluation of agent recommendations",
        summary: "Treating the agent itself as a system under evaluation — tracking how often its recommendations were approved versus dismissed, and eventually whether approved recommendations actually improved the outcome they targeted.",
        tradeoffs: "Without this feedback loop, there's no way to know if the agent is actually good at its job or just confident-sounding; a real version would need this history aggregated into approval-rate and calibration statistics over many rounds.",
        practicalUse: "Partially implemented: the Agent page now keeps a per-track history of past resolved cards with their outcomes, but nothing aggregates that history into an approval-rate or calibration statistic yet.",
        status: "simulated",
      },
    ],
  },
  {
    id: "azure-architecture",
    title: "Azure architecture",
    icon: Cloud,
    intro: "A production-shaped reference for where this console's services, secrets, and observability would live on Azure — none of it deployed yet.",
    concepts: [
      {
        id: "service-boundaries",
        title: "Service boundaries",
        summary: "Explicit lines separating the web frontend, the coordinator API, the federation engine, and each hospital client into independently deployable, independently securable units, rather than one undifferentiated application.",
        tradeoffs: "More boundaries mean more services to deploy and monitor, but each boundary is also a place to apply least privilege and to fail one component without taking down everything else.",
        practicalUse: "Documented in the proposed architecture (Container Apps for web/coordinator, isolated per-hospital client containers); this console currently runs as a single web app plus a single mock API server.",
        status: "simulated",
      },
      {
        id: "network-isolation",
        title: "Network isolation",
        summary: "Restricting which services can reach which other services at the network layer (private endpoints, virtual network integration) so, for example, the database isn't reachable from the public internet even if application-layer auth is somehow bypassed.",
        security: "Provides defense-in-depth against misconfigured or bypassed application-layer controls.",
        tradeoffs: "Private networking adds real setup and debugging complexity (DNS, peering, firewall rules).",
        practicalUse: "Documented as a required production boundary for the Azure deployment; not configured in this console's current environment.",
        status: "reserved",
      },
      {
        id: "identity-access-management",
        title: "Identity and access management",
        summary: "Verifying who a user or service is (authentication) and what they're allowed to do (authorization), ideally via a managed identity provider rather than custom-built credential handling.",
        tradeoffs: "A managed identity provider (Entra ID in production, Clerk in this console) offloads password handling, MFA, and session security, at the cost of a dependency on that provider's availability and roadmap.",
        practicalUse: "Implemented today via Clerk for authentication and session management, gating every dashboard route; the proposed production path swaps this for Microsoft Entra ID.",
        status: "implemented",
      },
      {
        id: "secrets-certificates",
        title: "Secrets and certificate management",
        summary: "Storing API keys, database credentials, and TLS certificates in a dedicated managed vault with access policies and rotation, rather than in code, config files, or environment variables checked into source control.",
        security: "Eliminates the most common real-world credential-leak vector: a secret committed to a repository.",
        tradeoffs: "A managed vault adds one more service dependency and retrieval latency at startup.",
        practicalUse: "Documented as an Azure Key Vault requirement for production; this console currently uses environment variables for its Clerk keys.",
        status: "reserved",
      },
      {
        id: "container-deployment",
        title: "Container deployment",
        summary: "Packaging each service as a container image with a pinned, reproducible runtime environment, then running it on a managed container platform that handles scaling and restarts.",
        tradeoffs: "Containerization adds a build/registry step to the deployment pipeline but removes environment drift and makes horizontal scaling straightforward.",
        practicalUse: "Documented as the target deployment model (Azure Container Apps or AKS for the coordinator and client simulators); no Dockerfiles or container configuration exist in this repository yet.",
        status: "reserved",
      },
      {
        id: "message-delivery",
        title: "Message delivery",
        summary: "Reliable, ordered or at-least-once delivery of events between services (e.g. a completed round notifying the dashboard) via a managed message broker, instead of services polling each other or relying on a single synchronous call that can be lost.",
        tradeoffs: "A message broker adds infrastructure and eventual-consistency reasoning, but decouples producers from consumers and survives a consumer being temporarily down.",
        practicalUse: "Documented as an Azure Service Bus requirement for production; this console's frontend currently polls REST endpoints directly with no broker in between.",
        status: "reserved",
      },
      {
        id: "realtime-updates",
        title: "Real-time updates",
        summary: "Pushing state changes to connected clients as they happen (via WebSockets or a managed pub/sub service) instead of the client polling and waiting for the next refresh interval.",
        tradeoffs: "Real-time push infrastructure is more complex to operate than polling but gives a genuinely live-feeling dashboard, which matters for an operations console people watch during a round.",
        practicalUse: "Documented as a candidate future addition (Azure Web PubSub or SignalR); this console currently relies on query refetching rather than a live push channel.",
        status: "reserved",
      },
      {
        id: "observability",
        title: "Observability",
        summary: "The combination of metrics, logs, and traces that let an operator understand what a distributed system is doing and why, typically centralized in a managed monitoring stack rather than scattered per-service log files.",
        tradeoffs: "Centralized observability tooling has ongoing cost proportional to log/metric volume, but is what makes a multi-service production incident diagnosable in minutes instead of hours.",
        practicalUse: "Documented as an Azure Monitor / Application Insights / Log Analytics requirement for production; this console's only current observability is its own in-app event log, not infrastructure-level telemetry.",
        status: "reserved",
      },
      {
        id: "backup-disaster-recovery",
        title: "Backup and disaster recovery",
        summary: "Regularly and automatically saving recoverable copies of critical state (databases, model artifacts) with a defined Recovery Point Objective and Recovery Time Objective, and a tested procedure for actually restoring from them.",
        tradeoffs: "Automated, tested backups cost storage and process discipline, but an untested backup is not meaningfully different from no backup when disaster recovery is actually needed.",
        practicalUse: "The API now persists to a real Postgres database (tracks, nodes, events, agent assessments), but no automated backup or point-in-time recovery is configured against it yet — the production Postgres Flexible Server template documents that requirement, it doesn't satisfy it.",
        status: "reserved",
      },
      {
        id: "cost-scaling",
        title: "Cost and scaling considerations",
        summary: "Sizing infrastructure and choosing managed-service tiers to match actual load and budget, and designing so scaling up (more hospitals, more concurrent users) is a configuration change, not a rearchitecture.",
        tradeoffs: "Over-provisioning for hypothetical future scale wastes budget at pilot stage; under-provisioning risks a rearchitecture later.",
        practicalUse: "This console is explicitly scoped to a 10-node pilot; no autoscaling or cost-tier configuration exists yet because there is no real infrastructure deployed.",
        status: "reserved",
      },
      {
        id: "hospital-connectivity",
        title: "Hospital-site connectivity",
        summary: "How an actual hospital's local client service reaches the cloud coordinator — typically outbound-only connections initiated from inside the hospital network, since hospital IT rarely allows inbound connections from the public internet.",
        tradeoffs: "Outbound-only connectivity is far easier for a hospital's security team to approve than an inbound firewall exception, but it constrains the coordinator to request/response or long-poll patterns rather than freely pushing to clients.",
        practicalUse: "Documented as the intended production topology (each hospital runs its own local client service, connecting outbound to Azure); this console's 10 clients are simulated entirely server-side with no real network boundary between them.",
        status: "reserved",
      },
      {
        id: "data-residency",
        title: "Data residency",
        summary: "Legal and contractual requirements that certain data must be processed or stored within a specific geographic or jurisdictional boundary (e.g. patient data staying within the country or region it was collected in).",
        tradeoffs: "Respecting data residency can mean deploying regional infrastructure per jurisdiction rather than one global deployment.",
        practicalUse: "Directly relevant to this platform's design principle that raw imaging never leaves its originating site at all — the strongest possible residency posture — but formal jurisdictional compliance mapping is not implemented.",
        status: "reserved",
      },
    ],
  },
];

export function conceptStatusLabel(status: ConceptStatus): string {
  if (status === "implemented") return "Implemented";
  if (status === "simulated") return "Simulated";
  return "Reserved for production";
}
