import { shadcn } from '@clerk/themes';
import { basePath } from '@/lib/auth';

export const clerkAppearance = {
  theme: shadcn,
  cssLayerName: 'clerk',
  options: {
    logoPlacement: 'inside' as const,
    logoLinkUrl: basePath || '/',
    logoImageUrl: `${window.location.origin}${basePath}/logo.svg`,
    socialButtonsPlacement: 'bottom' as const,
  },
  variables: {
    colorPrimary: 'hsl(166 48% 34%)',
    colorForeground: 'hsl(201 31% 19%)',
    colorMutedForeground: 'hsl(201 15% 43%)',
    colorDanger: 'hsl(2 64% 42%)',
    colorBackground: 'hsl(42 34% 98%)',
    colorInput: 'hsl(42 28% 94%)',
    colorInputForeground: 'hsl(201 31% 19%)',
    colorNeutral: 'hsl(42 16% 82%)',
    borderRadius: '0.7rem',
    fontFamily: 'Manrope, sans-serif',
  },
  elements: {
    rootBox: 'w-full flex justify-center',
    cardBox: 'bg-[hsl(42_34%_98%)] rounded-2xl w-[440px] max-w-full overflow-hidden',
    card: '!shadow-none !border-0 !bg-transparent !rounded-none',
    footer: '!shadow-none !border-0 !bg-transparent !rounded-none',
    headerTitle: 'font-display tracking-[-.04em]',
    headerSubtitle: 'text-[hsl(201_15%_43%)]',
    socialButtonsBlockButtonText: 'text-[hsl(201_31%_19%)]',
    formFieldLabel: 'text-[hsl(201_31%_19%)]',
    footerActionLink: 'text-[hsl(166_48%_34%)]',
    footerActionText: 'text-[hsl(201_15%_43%)]',
    dividerText: 'text-[hsl(201_15%_43%)]',
    identityPreviewEditButton: 'text-[hsl(166_48%_34%)]',
    formFieldSuccessText: 'text-[hsl(166_48%_34%)]',
    alertText: 'text-[hsl(2_64%_42%)]',
    logoBox: 'h-10',
    logoImage: 'h-9 w-auto',
    socialButtonsBlockButton: 'border-[hsl(42_16%_82%)] bg-white',
    formButtonPrimary: 'bg-[hsl(201_31%_19%)] hover:bg-[hsl(201_31%_24%)]',
    formFieldInput: 'border-[hsl(42_16%_82%)] bg-[hsl(42_28%_94%)] text-[hsl(201_31%_19%)]',
    footerAction: 'border-t border-[hsl(42_16%_82%)]',
    dividerLine: 'bg-[hsl(42_16%_82%)]',
    alert: 'border-[hsl(2_64%_42%/.2)] bg-[hsl(2_64%_42%/.08)]',
    otpCodeFieldInput: 'border-[hsl(42_16%_82%)] bg-[hsl(42_28%_94%)]',
    formFieldRow: 'gap-2',
    main: 'gap-5',
  },
};